elastic/ansible-beats

.ci/jobs/defaults.yml, .ci/jobs/elastic+ansible-beats+master.yml, .ci/jobs/elastic+ansible-beats+pull-request.yml
Add JJBB job definitions to the repo so they can be managed here.
=> [ci] add jjbb job definitions

.ci/jobs/defaults.yml
this file path should be consistent with runbld configuration
=> [ci] fix matrix.yml file path

filter_plugins/custom.py, tasks/beats-config.yml
this fix part 2 of #31 : conflict on custom filter file name.
=> replace custom filter with yml handling

.github/stale.yml
=> [botelastic] fix probot newlines

CHANGELOG.md, README.md, defaults/main.yml, test/integration/standard-6x.yml
=> 7.4.1 release

helpers/bumper.py
Add script to bump Beats versions before release
=> add bumper script

CHANGELOG.md, README.md, defaults/main.yml, helpers/bumper.py
=> 7.5.0 release

CHANGELOG.md, README.md, defaults/main.yml, helpers/bumper.py, test/integration/standard-6x.yml
=> 7.5.1 release

.ci/jobs/elastic+ansible-beats+master.yml, .ci/jobs/elastic+ansible-beats+pull-request.yml
Bump ruby used for kitchen tests from 2.3.0 to 2.5.7
=> [ci] bump ruby to 2.5.7

CHANGELOG.md, README.md, defaults/main.yml, helpers/bumper.py
=> 7.5.2 release

README.md
If not - just ignore the PR :)
=> Fixed a typo Betas is probably meant to be Beats instead

CHANGELOG.md, README.md, defaults/main.yml, helpers/bumper.py
=> 7.6.0 release

CHANGELOG.md, README.md, defaults/main.yml, helpers/bumper.py, test/integration/standard-6x.yml
=> 7.6.1 release

README.md, tasks/beats-config.yml, tasks/beats-param-check.yml
=> add task to create directory for default policies

CHANGELOG.md, README.md, defaults/main.yml, helpers/bumper.py, test/integration/standard-6x.yml
=> 7.6.2 release

.kitchen.yml
Related to https://github.com/elastic/ansible-beats/pull/85#issuecomment-628072509
=> [meta] use epel repo to install ansible

CHANGELOG.md, README.md, defaults/main.yml, helpers/bumper.py, test/integration/standard-6x.yml
* 7.7.0 as default version
* 6.8.9 as 6.x tested version
=> 7.7.0 release

CHANGELOG.md, README.md, defaults/main.yml, helpers/bumper.py
=> 7.8.0 release

CHANGELOG.md, README.md, defaults/main.yml, helpers/bumper.py, test/integration/standard-6x.yml
* 7.8.1 as default version
* 6.8.11 as 6.x tested version
| PR                                                      | Author                             | Title                    |
|---------------------------------------------------------|------------------------------------|--------------------------|
| [#89](https://github.com/elastic/ansible-beats/pull/89) | [@jmlrt](https://github.com/jmlrt) | Add amazonlinux2 support |
=> 7.8.1 release

CHANGELOG.md, README.md, defaults/main.yml, helpers/bumper.py, test/integration/standard-6x.yml
* 7.9.0 as default version
* 6.8.12 as 6.x tested version
=> 7.9.0 release (#97)

.kitchen.yml, CHANGELOG.md, README.md, defaults/main.yml, test/integration/standard-6x.yml
* 7.9.3 as default version.
* 6.8.13 as 6.x tested version
=> 7.9.3 release

CHANGELOG.md, README.md, defaults/main.yml
* 7.10.0 as default version.
| [#113](https://github.com/elastic/ansible-beats/pull/113) | [@jmlrt](https://github.com/jmlrt) | [meta] clean deprecated bumper script  |
=> 7.10.0 release

vars/Debian.yml, vars/RedHat.yml
This variable is no more used anywhere in the role
=> Cleanup init_script variable

CHANGELOG.md, README.md, defaults/main.yml
=> 7.10.2 release

CHANGELOG.md, README.md, defaults/main.yml, test/integration/standard-6x.yml
* 7.11.1 as default version.
* 6.8.14 as 6.x tested version
=> 7.11.1 release

.gitignore, .kitchen.yml, README.md, test/matrix.yml
Enable test-kitchen configuration for the below OS:
- Debian-10
=> Support debian 10

CHANGELOG.md, README.md, defaults/main.yml
=> 7.12.1 release

CHANGELOG.md, README.md, defaults/main.yml, test/integration/standard-6x.yml
* 7.13.0 as the default version.
* 6.8.16 as 6.x tested version
=> 7.13.0 release

CHANGELOG.md, README.md, defaults/main.yml
* 7.13.1 as default version.
| [#146](https://github.com/elastic/ansible-beats/pull/146) | [@jmlrt](https://github.com/jmlrt) | Fix unhold issue with custom deb packages  |
=> 7.13.1 release

CHANGELOG.md, README.md, defaults/main.yml
=> 7.13.2 release

CHANGELOG.md, README.md, defaults/main.yml
=> 7.13.4 release

CHANGELOG.md, README.md, defaults/main.yml, test/integration/standard-6x.yml
* 7.14.0 as default version.
* 6.8.18 as 6.x tested version
=> 7.14.0 release

CHANGELOG.md, README.md, defaults/main.yml
=> 7.15.0 release

CHANGELOG.md, README.md, defaults/main.yml
=> 7.16.0 release

tasks/beats-debian.yml
Sorry for this PR, but this annoying me a lot.
=> Remove duplicated space

CHANGELOG.md, README.md, defaults/main.yml, test/integration/standard-6x.yml
* 7.16.2 as default version.
* 6.8.22 as 6.x tested version
=> 7.16.2 release

CHANGELOG.md, README.md, defaults/main.yml, test/integration/standard-6x.yml
* 7.16.3 as default version.
* 6.8.23 as 6.x tested version
=> 7.16.3 release
