Gemfile.lock

This should fix vulnerability on ffi and rubyzip dependencies (cf. https://nvd.nist.gov/vuln/detail/CVE-2018-1000544 and https://nvd.nist.gov/vuln/detail/CVE-2018-1000201)

[gem] update dependencies

---

.kitchen.yml
README.md
defaults/main.yml
tasks/beats-debian.yml
tasks/beats-redhat.yml
templates/beats.repo.j2
test/integration/multi.yml
test/integration/standard-6x.yml
test/integration/standard-6x/serverspec/default_spec.rb
test/integration/standard.yml
test/matrix.yml
vars/Debian.yml
vars/RedHat.yml

This PR add support for beats 7.x
⚠️ beats 6.x is introducing breaking changes in configuration:
- `filebeat.input_types` is replaced by `filebeat.type` (https://github.com/elastic/beats/pull/4294)
⚠️ beats 7.x is introducing breaking changes in configuration:
- `filebeat.prospectors` is replaced by `filebeat.inputs` (https://github.com/elastic/beats/pull/8909)
Kitchen [standard scenario](https://github.com/elastic/ansible-beats/compare/beats-7.x?expand=1#diff-6053bb4c6dcac36bb0d2e2034f229127) is no more compatible with all all major versions.

[7.x] add support for beats 7.x

---

meta/main.yml

Galaxy role name is [ansible_beats](https://galaxy.ansible.com/elastic/ansible_beats) since Ansible Galaxy v3.0 no longer perform name calculation by removing `ansible` prefix (https://galaxy.ansible.com/docs/contributing/creating_role.html#role-names).
Also adding some more relevant tags.

[galaxy] fix role name

---

vars/main.yml

As es_conf_dir is not used anywhere in the role, we should remove it.
As it conflict with ansible.elasticsearch variable definition, we need to remove it.
fix #31

remove unused es_conf_dir variable

---

handlers/main.yml
tasks/beats-config.yml
tasks/beats-debian.yml
tasks/beats-redhat.yml
tasks/beats.yml

When running more than one role at once, make sure all of the right notifies
get triggered, not just the one for the last beat role run.

Make sure the right beat service gets restarted

---

.github/issue_template.md
.github/stale.yml

This PR add [Probot](https://probot.github.io/) configuration to manage stale issues/PR:
- Issues / PR will be marked as stale (with a `triage/stale` label) after 90 days without any activity.
- Stale issues / PR will be closed automatically after 30 days without any activity.
Also add a GitHub Issue template inspired by [elastic/ansible-elasticsearch/.github/issue_template.md](https://github.com/elastic/ansible-elasticsearch/blob/master/.github/issue_template.md)

Add probot config to manage stale issues/pr + GH issue template

---

README.md

- Adapt README file to make it more consistent with [ansible-elasticsearch](https://github.com/elastic/ansible-elasticsearch) README file
- Add more details about how to install different Beats products / version - related to https://github.com/elastic/ansible-elasticsearch/pull/614#issue-317208596
- Remove some obsolete details

[doc] enhance ansible-beats doc

---

handlers/main.yml
tasks/beats-config.yml
tasks/beats-debian.yml
tasks/beats-redhat.yml
tasks/beats.yml
tasks/main.yml

Rename the handlers

---

README.md
defaults/main.yml
helpers/bumper.py
test/integration/standard-6x.yml

Update beats default versions:
- 6.8.4 => 6.8.5
- 7.4.1 => 7.4.2

bump beats to 6.8.5 and 7.4.2

---

meta/main.yml
tasks/beats-config.yml
tasks/beats.yml
templates/beat.yml.j2
test/integration/config.yml

In order to offer additional configuration possibilities which we use internally, I have extended the template accordingly by the variable `bead_additional_conf`. So it is possible to create any beat configuration.
Furthermore our lint test showed some bugs which will be fixed with the second commit.
I would be happy about a merge!

beat config improvements

---

README.md

related to elastic/ansible-elasticsearch#657

[doc] switched relative URLs to absolute URLs

---

README.md

Filebeat example in the README is using the old configuration syntax, this PR fix it.
Related to https://github.com/elastic/ansible-beats/issues/70#issuecomment-579442276

[doc] fix filebeat example configuration

---

README.md
defaults/main.yml
tasks/beats-debian.yml
tasks/beats-redhat.yml

Sometimes, we already have repo of elastic deployed on servers.
This PR add the option to disable the addition of repos.
I remove too the installation of yum lock package if it is no needed.

Add option for disable the repo installation and lock package installation

---

.kitchen.yml
README.md
test/matrix.yml

Amazon Linux 2 support will be added for ansible-elasticsearch in https://github.com/elastic/ansible-elasticsearch/pull/703 thanks to @anisf, so let's add it also to ansible-beats

add amazonlinux2 support

---

.ci/jobs/defaults.yml
.ci/jobs/elastic+ansible-beats+master.yml

This PR add Slack notifications to Elastic Release team Slack channel for [elastic+ansible-beats+master](https://devops-ci.elastic.co/job/elastic+ansible-beats+master/) test job.

[meta] add slack notifications to CI jobs

---

.ci/jobs/elastic+ansible-beats+master.yml

This commit adds a new auth-token-credential-id entry in addition of auth-token-id for slack token.
This is due to a bug in JJB which requires having both entries to prevent having an empty authTokenCredentialId in job config.xml (https://storyboard.openstack.org/#!/story/2007953).

[meta] add auth-token-credential-id entry for slack

---

.kitchen.yml
README.md
test/matrix.yml

Enable test-kitchen configuration for the below OS:
- CentOS-8
This is WIP
Closes https://github.com/elastic/ansible-beats/issues/111

Support CentOS-8

---

.kitchen.yml
README.md
tasks/beats-redhat.yml
test/matrix.yml

This commit remove CentOS 6 support which is EOL since 2020-11-30.

Remove CentOS 6 support

---

CHANGELOG.md
README.md
defaults/main.yml

* 7.10.1 as default version.
| [#115](https://github.com/elastic/ansible-beats/pull/115) | [@v1v](https://github.com/v1v) | Support CentOS-8  |

7.10.1 release

---

README.md

This commit fix the Ansible Galaxy install command to use the new
versioning implemented in 7.10.1 release.
ansible-beats tags are now prefixed by `v` which makes Ansible Galaxy
versions also including this prefix.
Fix #121

[meta] fix ansible galaxy install command

---

tasks/beats-config.yml

This commit update ILM policy file tasks to use root permission, so
we can write policies files to directories with root only permissions
like `/etc/filebeat/` or `/var/lib/filebeat/` for example.
Fix #117

Copy ILM policy file with root permission

---

.kitchen.yml
README.md
test/matrix.yml

Remove support for Ubuntu-14.04
EOL for `Ubuntu.14.04`: April 30th 2019

Remove Ubuntu-14.04 support

---

meta/main.yml

CentOS 6 was removed with https://github.com/elastic/ansible-beats/pull/120 so let's update the metadata

Update metadata reference for CentOS 8

---

CHANGELOG.md
README.md
defaults/main.yml
test/integration/standard-6x.yml

* 7.12.0 as default version.
* 6.8.15 as 6.x tested version
| [#138](https://github.com/elastic/ansible-beats/pull/138) | [@jmlrt](https://github.com/jmlrt) | [meta] fix changelog after 7.11.2 release  |

7.12.0 release

---

meta/main.yml
tasks/beats-debian.yml

This commit fix an issue where unholding package fails when using a
custom package url instead of Elastic repository and beat package isn't
installed yet.
Also replace `apt-mark` shell commands by `dpkg_selections` module.
Fix #83

Fix unhold issue with custom deb packages

---

tasks/beats-config.yml

Can be useful to keep a backup of the file in case of rollback

Backup the existing configuration file

---

CHANGELOG.md
README.md
defaults/main.yml
test/integration/standard-6x.yml

* 7.13.3 as default version.
* 6.8.17 as 6.x tested version
| [#148](https://github.com/elastic/ansible-beats/pull/148) | [@metabsd](https://github.com/metabsd) | Backup the existing configuration file  |

7.13.3 release

---

README.md

This commit adds a warning message to the README to
notify users that the role will be deprecated.

Add warning message about 8.x versions

---

CHANGELOG.md
README.md
defaults/main.yml
test/integration/standard-6x.yml

* 7.16.1 as default version.
* 6.8.21 as 6.x tested version
| [#166](https://github.com/elastic/ansible-beats/pull/166) | [@mgreau](https://github.com/mgreau) | Add warning message about 8.x versions  |
| [#164](https://github.com/elastic/ansible-beats/pull/164) | [@seadog007](https://github.com/seadog007) | Remove duplicated space  |

7.16.1 release

---

README.md
test/matrix.yml

This commit removes CentOS 8 tests. These tests are now failing because
CentOS 8 is now EOL and it's repositories have been archived.
Source: https://forums.centos.org/viewtopic.php?f=54&t=78708

Remove CentOS 8 tests
